spring:
  application:
    name: eureka-server
server:
  port: 3001
eureka:
  instance:
    hostname: eureka3001.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka3002.com:3002/eureka/