spring:
  application:
    name: eureka-web
server:
  port: 3009
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://eureka3001.com:3001/eureka/,http://eureka3002.com:3002/eureka/