spring:
  application:
    name: eureka-server
server:
  port: 3002
eureka:
  instance:
    hostname: eureka3002.com
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka3001.com:3001/eureka/